export const actionTypes = {
    //user

    PROCESS_ACTION: "PROCESS_ACTION",
    PROCESS_ACTION_FAILED: "PROCESS_ACTION_FAILED",
    FETCH_ALL_POSTS_SUCCESS: "FETCH_ALL_POSTS_SUCCESS",
    EDIT_POST_SUCCESS: "EDIT_POST_SUCCESS",
    DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
    CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS"
}